POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

fullName = Euro &
code = EUR &
sign = €


###
GET http://localhost:8080/currencies



###
GET http://localhost:8080/exchangeRates

###
GET http://localhost:8080/exchangeRate/JPYUSD

###
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode = EUR &
targetCurrencyCode = JPY &
rate = 171.97

